// Mock data for CafeDesk Management System

export const menuItems = [
  {
    id: 1,
    name: "Espresso",
    category: "Drinks",
    price: 3.50,
    description: "Rich and bold coffee shot",
    image: "coffee espresso dark",
    available: true,
  },
  {
    id: 2,
    name: "Cappuccino",
    category: "Drinks",
    price: 4.50,
    description: "Espresso with steamed milk foam",
    image: "cappuccino coffee art",
    available: true,
  },
  {
    id: 3,
    name: "Latte",
    category: "Drinks",
    price: 4.75,
    description: "Smooth espresso with steamed milk",
    image: "latte coffee art",
    available: true,
  },
  {
    id: 4,
    name: "Cold Brew",
    category: "Drinks",
    price: 5.00,
    description: "Smooth cold-steeped coffee",
    image: "cold brew coffee glass",
    available: true,
  },
  {
    id: 5,
    name: "Croissant",
    category: "Snacks",
    price: 3.00,
    description: "Buttery flaky pastry",
    image: "croissant pastry golden",
    available: true,
  },
  {
    id: 6,
    name: "Blueberry Muffin",
    category: "Snacks",
    price: 3.50,
    description: "Fresh baked muffin with blueberries",
    image: "blueberry muffin fresh",
    available: true,
  },
  {
    id: 7,
    name: "Avocado Toast",
    category: "Meals",
    price: 8.50,
    description: "Sourdough toast with fresh avocado",
    image: "avocado toast rustic",
    available: true,
  },
  {
    id: 8,
    name: "Caesar Salad",
    category: "Meals",
    price: 9.50,
    description: "Crisp romaine with parmesan",
    image: "caesar salad fresh",
    available: true,
  },
  {
    id: 9,
    name: "Club Sandwich",
    category: "Meals",
    price: 10.00,
    description: "Triple-decker with turkey and bacon",
    image: "club sandwich gourmet",
    available: true,
  },
  {
    id: 10,
    name: "Green Tea",
    category: "Drinks",
    price: 3.00,
    description: "Premium green tea",
    image: "green tea ceramic cup",
    available: false,
  },
];

export const orders = [
  {
    id: "ORD-001",
    tableNumber: 5,
    customerName: "John Doe",
    items: [
      { itemId: 2, itemName: "Cappuccino", quantity: 2, price: 4.50 },
      { itemId: 5, itemName: "Croissant", quantity: 1, price: 3.00 },
    ],
    total: 12.00,
    status: "pending",
    timestamp: "2026-01-30T10:30:00",
  },
  {
    id: "ORD-002",
    tableNumber: 3,
    customerName: "Jane Smith",
    items: [
      { itemId: 7, itemName: "Avocado Toast", quantity: 1, price: 8.50 },
      { itemId: 4, itemName: "Cold Brew", quantity: 1, price: 5.00 },
    ],
    total: 13.50,
    status: "preparing",
    timestamp: "2026-01-30T11:15:00",
  },
  {
    id: "ORD-003",
    tableNumber: 8,
    customerName: "Mike Johnson",
    items: [
      { itemId: 9, itemName: "Club Sandwich", quantity: 1, price: 10.00 },
      { itemId: 3, itemName: "Latte", quantity: 2, price: 4.75 },
    ],
    total: 19.50,
    status: "ready",
    timestamp: "2026-01-30T11:45:00",
  },
  {
    id: "ORD-004",
    tableNumber: 2,
    customerName: "Sarah Williams",
    items: [
      { itemId: 8, itemName: "Caesar Salad", quantity: 1, price: 9.50 },
    ],
    total: 9.50,
    status: "completed",
    timestamp: "2026-01-30T09:30:00",
  },
];

export const inventory = [
  {
    id: 1,
    name: "Coffee Beans",
    category: "Beverages",
    quantity: 45,
    unit: "kg",
    minStock: 20,
    status: "in-stock",
  },
  {
    id: 2,
    name: "Milk",
    category: "Beverages",
    quantity: 80,
    unit: "liters",
    minStock: 50,
    status: "in-stock",
  },
  {
    id: 3,
    name: "Sugar",
    category: "Beverages",
    quantity: 15,
    unit: "kg",
    minStock: 25,
    status: "low-stock",
  },
  {
    id: 4,
    name: "Bread",
    category: "Food",
    quantity: 30,
    unit: "loaves",
    minStock: 20,
    status: "in-stock",
  },
  {
    id: 5,
    name: "Avocados",
    category: "Food",
    quantity: 8,
    unit: "pieces",
    minStock: 15,
    status: "low-stock",
  },
  {
    id: 6,
    name: "Lettuce",
    category: "Food",
    quantity: 5,
    unit: "heads",
    minStock: 10,
    status: "critical",
  },
  {
    id: 7,
    name: "Tea Leaves",
    category: "Beverages",
    quantity: 12,
    unit: "kg",
    minStock: 8,
    status: "in-stock",
  },
  {
    id: 8,
    name: "Croissants",
    category: "Pastry",
    quantity: 25,
    unit: "pieces",
    minStock: 20,
    status: "in-stock",
  },
];

export const employees = [
  {
    id: 1,
    name: "Alice Cooper",
    role: "Barista",
    email: "alice@cafedesk.com",
    phone: "+1-555-0101",
    shift: "Morning",
    status: "active",
  },
  {
    id: 2,
    name: "Bob Martin",
    role: "Waiter",
    email: "bob@cafedesk.com",
    phone: "+1-555-0102",
    shift: "Evening",
    status: "active",
  },
  {
    id: 3,
    name: "Carol White",
    role: "Chef",
    email: "carol@cafedesk.com",
    phone: "+1-555-0103",
    shift: "Morning",
    status: "active",
  },
  {
    id: 4,
    name: "David Brown",
    role: "Manager",
    email: "david@cafedesk.com",
    phone: "+1-555-0104",
    shift: "Full-day",
    status: "active",
  },
];

export const bills = [
  {
    id: "BILL-001",
    orderId: "ORD-004",
    customerName: "Sarah Williams",
    tableNumber: 2,
    amount: 9.50,
    paymentMethod: "Card",
    status: "paid",
    date: "2026-01-30",
  },
  {
    id: "BILL-002",
    orderId: "ORD-001",
    customerName: "John Doe",
    tableNumber: 5,
    amount: 12.00,
    paymentMethod: "Cash",
    status: "pending",
    date: "2026-01-30",
  },
  {
    id: "BILL-003",
    orderId: "ORD-002",
    customerName: "Jane Smith",
    tableNumber: 3,
    amount: 13.50,
    paymentMethod: "Card",
    status: "pending",
    date: "2026-01-30",
  },
];

export const tables = [
  { number: 1, capacity: 2, status: "available" },
  { number: 2, capacity: 4, status: "occupied" },
  { number: 3, capacity: 4, status: "occupied" },
  { number: 4, capacity: 2, status: "available" },
  { number: 5, capacity: 6, status: "occupied" },
  { number: 6, capacity: 2, status: "available" },
  { number: 7, capacity: 4, status: "reserved" },
  { number: 8, capacity: 4, status: "occupied" },
];

export const kpiData = {
  totalSales: 1245.50,
  totalOrders: 42,
  inventoryAlerts: 3,
  pendingBills: 2,
  todayRevenue: 485.00,
  activeOrders: 8,
};
